url: http://shrimasterbatches.com
baseurl: '/agency-jekyll-theme/'

# Site settings
title: Shri Masterbatches
email: contact@shrimasterbatches.com
description: "Top Quality Filler Masterbatches and CaCO3 powder"


# Team names, titles and social links
people:
- name: Shrikanth Kulkarni
  pic: 1
  position: CEO
  social:
    - title: gmail
      url: contact@shrimasterbatches.com


# Postal address (add as many lines as necessary)
address:
  - line: No. 295 Siddalingeshwara Layout, JP Nagar
  - line: Mysore, India - 570008

# Build settings
markdown: kramdown
permalink: pretty
